server:
  port: 9029
spring:
  application:
    name: DayCareBooking
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Rajesh@6301259439
    url: jdbc:mysql://localhost:3306/petexproject
    username: root
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hybernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
