logging:
  level:
    org:
      hibernate:
        SQL: INFO
server:
  port: 9015
spring:
  banner:
    charset: 'UTF-8 '
  datasource:
    password: Rajesh@6301259439
    url: jdbc:mysql://localhost:3306/petexproject
    username: root
  jpa:
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 1GB  # Set the maximum file size to 1GB
      max-request-size: 1GB  # Set the maximum request size to 1GB
  thymeleaf:
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
