server:
  port: 1115
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: Rajesh@6301259439
    url: jdbc:mysql://localhost:3306/petexproject
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
