server:
  port: 9003
spring:
  datasource:
    password: Rajesh@6301259439
    url: jdbc:mysql://localhost:3306/PetexProject
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mvc:
    dispatch-options-request: true
